version: 2
updates:
  # Main Flutter project
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "flutter"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    reviewers:
      - "fulleni"

  # All packages (including nested) in packages directory
  - package-ecosystem: "pub"
    directory: "/packages/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "packages"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      dev-dependencies:
        dependency-type: "development"
    reviewers:
      - "fulleni"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 10
