name: taskmaster
description: A new Flutter project named TaskMaster.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  local_storage_todos_client:
    path: ./packages/todos/local_storage_todos_client
  shared_preferences: ^2.4.0
  todos_client:
    path: ./packages/todos/todos_client
  todos_repository:
    path: ./packages/todos/todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/