name: taskmaster
description: TaskMaster is a user-friendly task management application built with Flutter, designed to help you stay organized and productive.
publish_to: "none"
version: 0.9.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  local_storage_todos_client:
    path: ./packages/todos/local_storage_todos_client
  local_storage_user_preferences_client:
    path: ./packages/user_preferences/local_storage_user_preferences_client
  shared_preferences: ^2.4.0
  todos_repository:
    path: ./packages/todos/todos_repository
  user_preferences_repository:
    path: ./packages/user_preferences/user_preferences_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  generate: true
