name: local_storage_user_preferences_client
description: "A UserPreferencesClient implementation that uses the local storage."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.0.6
  user_preferences_client:
    path: ../user_preferences_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  mocktail: ^1.0.4
