name: user_preferences_client
description: "Handles all user preferences for the client side of the application."
version: 0.3.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
