name: user_preferences_client
description: "Handles all user preferences for the client side of the application."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

