name: todos_repository
description: A repository that handles todo related requests.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
 todos_client:
    path: ../todos_client
  
dev_dependencies:
 mocktail: ^1.0.4
  
 test: ^1.25.14
