name: Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: 
          - "."
          - "packages/**"
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.folder }}
      
      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.folder }}
